//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Python.LanguageServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Python.LanguageServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing workspace, {0} items remaining....
        /// </summary>
        internal static string AnalysisProgress_MultipleItemsRemaining {
            get {
                return ResourceManager.GetString("AnalysisProgress_MultipleItemsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing workspace, 1 item remaining....
        /// </summary>
        internal static string AnalysisProgress_SingleItemRemaining {
            get {
                return ResourceManager.GetString("AnalysisProgress_SingleItemRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename.
        /// </summary>
        internal static string RenameVariable_CannotRename {
            get {
                return ResourceManager.GetString("RenameVariable_CannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename modules.
        /// </summary>
        internal static string RenameVariable_CannotRenameModuleName {
            get {
                return ResourceManager.GetString("RenameVariable_CannotRenameModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information is available for the variable &apos;{0}&apos;..
        /// </summary>
        internal static string RenameVariable_NoInformationAvailableForVariable {
            get {
                return ResourceManager.GetString("RenameVariable_NoInformationAvailableForVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a symbol to be renamed..
        /// </summary>
        internal static string RenameVariable_SelectSymbol {
            get {
                return ResourceManager.GetString("RenameVariable_SelectSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get analysis for the selected expression..
        /// </summary>
        internal static string RenameVariable_UnableGetExpressionAnalysis {
            get {
                return ResourceManager.GetString("RenameVariable_UnableGetExpressionAnalysis", resourceCulture);
            }
        }
    }
}
