//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Python.LanguageServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Python.LanguageServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis caching mode: {0}..
        /// </summary>
        internal static string AnalysisCacheLevel {
            get {
                return ResourceManager.GetString("AnalysisCacheLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code analysis is in progress....
        /// </summary>
        internal static string AnalysisIsInProgressHover {
            get {
                return ResourceManager.GetString("AnalysisIsInProgressHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis restarted..
        /// </summary>
        internal static string AnalysisRestarted {
            get {
                return ResourceManager.GetString("AnalysisRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified cache folder does not exist. Switching to default..
        /// </summary>
        internal static string Error_InvalidCachePath {
            get {
                return ResourceManager.GetString("Error_InvalidCachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing for generic interpreter.
        /// </summary>
        internal static string InitializingForGenericInterpreter {
            get {
                return ResourceManager.GetString("InitializingForGenericInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing for {0}.
        /// </summary>
        internal static string InitializingForPythonInterpreter {
            get {
                return ResourceManager.GetString("InitializingForPythonInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Python Language Server version {0}.
        /// </summary>
        internal static string LanguageServerVersion {
            get {
                return ResourceManager.GetString("LanguageServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched token &apos;{0}&apos; on line {1}; line formatting may not be accurate..
        /// </summary>
        internal static string LineFormatter_UnmatchedToken {
            get {
                return ResourceManager.GetString("LineFormatter_UnmatchedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python interpreter version not specified. Assuming latests 3.x..
        /// </summary>
        internal static string PythonInterpreterVersionNotSpecified {
            get {
                return ResourceManager.GetString("PythonInterpreterVersionNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading modules... .
        /// </summary>
        internal static string ReloadingModules {
            get {
                return ResourceManager.GetString("ReloadingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename.
        /// </summary>
        internal static string RenameVariable_CannotRename {
            get {
                return ResourceManager.GetString("RenameVariable_CannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace root: {0}.
        /// </summary>
        internal static string WorkspaceRoot {
            get {
                return ResourceManager.GetString("WorkspaceRoot", resourceCulture);
            }
        }
    }
}
