//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Python.Parsing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Python.Parsing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;as&apos; requires Python 2.6 or later.
        /// </summary>
        internal static string AsRequiresPython2dot6OrlaterErrorMsg {
            get {
                return ResourceManager.GetString("AsRequiresPython2dot6OrlaterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string expression part cannot include a backslash.
        /// </summary>
        internal static string BackslashFStringExpressionErrorMsg {
            get {
                return ResourceManager.GetString("BackslashFStringExpressionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;break&apos; outside loop.
        /// </summary>
        internal static string BreakOustideLoopErrorMsg {
            get {
                return ResourceManager.GetString("BreakOustideLoopErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t use starred expression here.
        /// </summary>
        internal static string CantUseStarredExpErrorMsg {
            get {
                return ResourceManager.GetString("CantUseStarredExpErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax, class decorators require 2.6 or later..
        /// </summary>
        internal static string ClassDecoratorsRequireTwodotSixErrorMsg {
            get {
                return ResourceManager.GetString("ClassDecoratorsRequireTwodotSixErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: closing parenthesis &apos;{0}&apos; does not match opening parenthesis &apos;{1}&apos;.
        /// </summary>
        internal static string ClosingParensNotMatchFStringErrorMsg {
            get {
                return ResourceManager.GetString("ClosingParensNotMatchFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;continue&apos; not properly in loop.
        /// </summary>
        internal static string ContinueNotInLoopErrorMsg {
            get {
                return ResourceManager.GetString("ContinueNotInLoopErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;continue&apos; not supported inside &apos;finally&apos; clause.
        /// </summary>
        internal static string ContinueNotSupportedInsideFinallyErrorMsg {
            get {
                return ResourceManager.GetString("ContinueNotSupportedInsideFinallyErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default &apos;except&apos; must be last.
        /// </summary>
        internal static string DefaultExceptMustBeLastErrorMsg {
            get {
                return ResourceManager.GetString("DefaultExceptMustBeLastErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default value must be specified here.
        /// </summary>
        internal static string DefaultValueMustBeSpecifiedErrorMsg {
            get {
                return ResourceManager.GetString("DefaultValueMustBeSpecifiedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate ** args arguments.
        /// </summary>
        internal static string DuplicateArgsDoubleArgumentErrorMsg {
            get {
                return ResourceManager.GetString("DuplicateArgsDoubleArgumentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate * args arguments.
        /// </summary>
        internal static string DuplicateArgsSingleArgumentErrorMsg {
            get {
                return ResourceManager.GetString("DuplicateArgsSingleArgumentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate argument &apos;{0}&apos; in function definition.
        /// </summary>
        internal static string DuplicateArgumentInFunctionDefinitionErrorMsg {
            get {
                return ResourceManager.GetString("DuplicateArgumentInFunctionDefinitionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate argument &apos;{0}&apos; in function definition.
        /// </summary>
        internal static string DuplicateArgumentInFunctionErrorMsg {
            get {
                return ResourceManager.GetString("DuplicateArgumentInFunctionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate keyword argument.
        /// </summary>
        internal static string DuplicateKeywordArgumentErrorMsg {
            get {
                return ResourceManager.GetString("DuplicateKeywordArgumentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: empty expression not allowed.
        /// </summary>
        internal static string EmptyExpressionFStringErrorMsg {
            get {
                return ResourceManager.GetString("EmptyExpressionFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected &apos;:&apos;.
        /// </summary>
        internal static string ExpectedColonErrorMsg {
            get {
                return ResourceManager.GetString("ExpectedColonErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected expression after del.
        /// </summary>
        internal static string ExpectedExpressionAfterDelErrorMsg {
            get {
                return ResourceManager.GetString("ExpectedExpressionAfterDelErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print statement expected expression to be printed.
        /// </summary>
        internal static string ExpectedExpressionToBePrintedErrorMsg {
            get {
                return ResourceManager.GetString("ExpectedExpressionToBePrintedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected an indented block.
        /// </summary>
        internal static string ExpectedIndentedBlockErrorMsg {
            get {
                return ResourceManager.GetString("ExpectedIndentedBlockErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected name.
        /// </summary>
        internal static string ExpectedNameErrorMsg {
            get {
                return ResourceManager.GetString("ExpectedNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: expecting &apos;{0}&apos; but found &apos;{1}&apos;.
        /// </summary>
        internal static string ExpectingCharButFoundFStringErrorMsg {
            get {
                return ResourceManager.GetString("ExpectingCharButFoundFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: expecting &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectingCharFStringErrorMsg {
            get {
                return ResourceManager.GetString("ExpectingCharFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax, from cause not allowed in 2.x..
        /// </summary>
        internal static string FromCauseNotAllowedIn2XErrorMsg {
            get {
                return ResourceManager.GetString("FromCauseNotAllowedIn2XErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to future feature is not defined: .
        /// </summary>
        internal static string FutureFeatureNotDefinedErrorMsg {
            get {
                return ResourceManager.GetString("FutureFeatureNotDefinedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from __future__ imports must occur at the beginning of the file.
        /// </summary>
        internal static string FutureImportsMustOccorAtBeginningOfFileErrorMsg {
            get {
                return ResourceManager.GetString("FutureImportsMustOccorAtBeginningOfFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to future statement does not support import *.
        /// </summary>
        internal static string FutureStatementDoesNotSupportImportErrorMsg {
            get {
                return ResourceManager.GetString("FutureStatementDoesNotSupportImportErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal target for annotation.
        /// </summary>
        internal static string IllegalTargetAnnotationErrorMsg {
            get {
                return ResourceManager.GetString("IllegalTargetAnnotationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import * only allowed at module level.
        /// </summary>
        internal static string ImportOnlyAllowedAtModuleErrorMsg {
            get {
                return ResourceManager.GetString("ImportOnlyAllowedAtModuleErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start location was not set correctly.
        /// </summary>
        internal static string IncorrectStartLocationErrorMsg {
            get {
                return ResourceManager.GetString("IncorrectStartLocationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: invalid conversion character: {0} expected &apos;s&apos;, &apos;r&apos;, or &apos;a&apos;.
        /// </summary>
        internal static string InvalidConversionCharacterExpectedFStringErrorMsg {
            get {
                return ResourceManager.GetString("InvalidConversionCharacterExpectedFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: invalid conversion character: expected &apos;s&apos;, &apos;r&apos;, or &apos;a&apos;.
        /// </summary>
        internal static string InvalidConversionCharacterFStringErrorMsg {
            get {
                return ResourceManager.GetString("InvalidConversionCharacterFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: invalid expression.
        /// </summary>
        internal static string InvalidExpressionFStringErrorMsg {
            get {
                return ResourceManager.GetString("InvalidExpressionFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid parameter.
        /// </summary>
        internal static string InvalidParameterErrorMsg {
            get {
                return ResourceManager.GetString("InvalidParameterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid sublist parameter.
        /// </summary>
        internal static string InvalidSublistParameterErrorMsg {
            get {
                return ResourceManager.GetString("InvalidSublistParameterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax, only exception value is allowed in 3.x..
        /// </summary>
        internal static string InvalidSyntaxAllowedInVersion3XErrorMsg {
            get {
                return ResourceManager.GetString("InvalidSyntaxAllowedInVersion3XErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax.
        /// </summary>
        internal static string InvalidSyntaxErrorMsg {
            get {
                return ResourceManager.GetString("InvalidSyntaxErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iterable argument unpacking follows keyword argument unpacking.
        /// </summary>
        internal static string IterableArgumentFollowsKeywordArgumentErrorMsg {
            get {
                return ResourceManager.GetString("IterableArgumentFollowsKeywordArgumentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iterable unpacking cannot be used in comprehension.
        /// </summary>
        internal static string IterableUnpackingErrorMsg {
            get {
                return ResourceManager.GetString("IterableUnpackingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords must come before ** args.
        /// </summary>
        internal static string KeywordsMustComeBeforeArgsErrorMsg {
            get {
                return ResourceManager.GetString("KeywordsMustComeBeforeArgsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: lambda must be inside parentheses.
        /// </summary>
        internal static string LambdaParenthesesFstringErrorMsg {
            get {
                return ResourceManager.GetString("LambdaParenthesesFstringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to misplaced yield.
        /// </summary>
        internal static string MisplacedYieldErrorMsg {
            get {
                return ResourceManager.GetString("MisplacedYieldErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing module name.
        /// </summary>
        internal static string MissingModuleNameErrorMsg {
            get {
                return ResourceManager.GetString("MissingModuleNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot mix bytes and nonbytes literals.
        /// </summary>
        internal static string MixingBytesAndNonBytesErrorMsg {
            get {
                return ResourceManager.GetString("MixingBytesAndNonBytesErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to named arguments must follow bare *.
        /// </summary>
        internal static string NamedArgumentsMustFollowBareErrorMsg {
            get {
                return ResourceManager.GetString("NamedArgumentsMustFollowBareErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use named assignment with {0}.
        /// </summary>
        internal static string NamedAssignmentWithErrorMsg {
            get {
                return ResourceManager.GetString("NamedAssignmentWithErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named expression must be parenthesized in this context.
        /// </summary>
        internal static string NamedExpressionCtxtErrorMsg {
            get {
                return ResourceManager.GetString("NamedExpressionCtxtErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-keyword arg after keyword arg.
        /// </summary>
        internal static string NonKeywordArgAfterKeywordArgErrorMsg {
            get {
                return ResourceManager.GetString("NonKeywordArgAfterKeywordArgErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonlocal declaration not allowed at module level.
        /// </summary>
        internal static string NonLocalDeclarationAtModuleErrorMsg {
            get {
                return ResourceManager.GetString("NonLocalDeclarationAtModuleErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a chance.
        /// </summary>
        internal static string NotAChanceErrorMsg {
            get {
                return ResourceManager.GetString("NotAChanceErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string expression part cannot include &apos;#&apos;.
        /// </summary>
        internal static string NumberSignFStringExpressionErrorMsg {
            get {
                return ResourceManager.GetString("NumberSignFStringExpressionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only one ** allowed.
        /// </summary>
        internal static string OnlyOneAllowedDoubleErrorMsg {
            get {
                return ResourceManager.GetString("OnlyOneAllowedDoubleErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only one * allowed.
        /// </summary>
        internal static string OnlyOneAllowedSingleErrorMsg {
            get {
                return ResourceManager.GetString("OnlyOneAllowedSingleErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax, parameter annotations require 3.x.
        /// </summary>
        internal static string ParameterAnnotationsRequire3dotXErrorMsg {
            get {
                return ResourceManager.GetString("ParameterAnnotationsRequire3dotXErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing already started. Use Restart to start again..
        /// </summary>
        internal static string ParsingAlreadyStartedErrorMsg {
            get {
                return ResourceManager.GetString("ParsingAlreadyStartedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to positional argument follows keyword argument.
        /// </summary>
        internal static string PositionalArgumentKeywardArgumentErrorMsg {
            get {
                return ResourceManager.GetString("PositionalArgumentKeywardArgumentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to positional argument follows keyword argument unpacking.
        /// </summary>
        internal static string PositionalArgumentKeywardArgumentUnpackingErrorMsg {
            get {
                return ResourceManager.GetString("PositionalArgumentKeywardArgumentUnpackingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to positional parameter after * args not allowed.
        /// </summary>
        internal static string PositionalParameterNotAllowedErrorMsg {
            get {
                return ResourceManager.GetString("PositionalParameterNotAllowedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax, return annotations require 3.x.
        /// </summary>
        internal static string ReturnAnnotationsRequire3dotXErrorMsg {
            get {
                return ResourceManager.GetString("ReturnAnnotationsRequire3dotXErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;return&apos; outside function.
        /// </summary>
        internal static string ReturnOutsideFunctionErrorMsg {
            get {
                return ResourceManager.GetString("ReturnOutsideFunctionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;return&apos; with argument inside generator.
        /// </summary>
        internal static string ReturnWithArgumentInGeneratorErrorMsg {
            get {
                return ResourceManager.GetString("ReturnWithArgumentInGeneratorErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax, set literals require Python 2.7 or later..
        /// </summary>
        internal static string SetLiteralsRequirePython2dot7ErrorMsg {
            get {
                return ResourceManager.GetString("SetLiteralsRequirePython2dot7ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: single &apos;}&apos; is not allowed.
        /// </summary>
        internal static string SingleClosedBraceFStringErrorMsg {
            get {
                return ResourceManager.GetString("SingleClosedBraceFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only single target (not tuple) can be annotated.
        /// </summary>
        internal static string SingleTargetCanBeAnnotatedErrorMsg {
            get {
                return ResourceManager.GetString("SingleTargetCanBeAnnotatedErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sublist parameters are not supported in 3.x.
        /// </summary>
        internal static string SublistParametersNotSupported3dotXErrorMsg {
            get {
                return ResourceManager.GetString("SublistParametersNotSupported3dotXErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syntax error.
        /// </summary>
        internal static string SyntaxErrorMsg {
            get {
                return ResourceManager.GetString("SyntaxErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two starred expressions in assignment.
        /// </summary>
        internal static string TwoStarredExpressionErrorMsg {
            get {
                return ResourceManager.GetString("TwoStarredExpressionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected end of file.
        /// </summary>
        internal static string UnexpectedEndOfFileErrorMsg {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected EOF while parsing.
        /// </summary>
        internal static string UnexpectedEndOfFileWhileParsingErrorMsg {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFileWhileParsingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected indent.
        /// </summary>
        internal static string UnexpectedIndentErrorMsg {
            get {
                return ResourceManager.GetString("UnexpectedIndentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected token &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedTokenErrorMsg {
            get {
                return ResourceManager.GetString("UnexpectedTokenErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled string token.
        /// </summary>
        internal static string UnhandledStringTokenErrorMsg {
            get {
                return ResourceManager.GetString("UnhandledStringTokenErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding problem: unknown encoding (line {0}).
        /// </summary>
        internal static string UnknownEncodingErrorMsg {
            get {
                return ResourceManager.GetString("UnknownEncodingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: unmatched &apos;{0}&apos;.
        /// </summary>
        internal static string UnmatchedFStringErrorMsg {
            get {
                return ResourceManager.GetString("UnmatchedFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file has both Unicode marker and PEP-263 file encoding.  You must use \&quot;utf-8\&quot; as the encoding name when a BOM is present..
        /// </summary>
        internal static string Utf8EncodingErrorMsg {
            get {
                return ResourceManager.GetString("Utf8EncodingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;, variable&quot; not allowed in 3.x - use &quot;as variable&quot; instead..
        /// </summary>
        internal static string VariableIn3dotXErrorMsg {
            get {
                return ResourceManager.GetString("VariableIn3dotXErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;yield&apos; inside async function.
        /// </summary>
        internal static string YieldInsideAsyncErrorMsg {
            get {
                return ResourceManager.GetString("YieldInsideAsyncErrorMsg", resourceCulture);
            }
        }
    }
}
