//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Python.Parsing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Python.Parsing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string expression part cannot include a backslash.
        /// </summary>
        internal static string BackslashFStringExpressionErrorMsg {
            get {
                return ResourceManager.GetString("BackslashFStringExpressionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: closing parenthesis &apos;{0}&apos; does not match opening parenthesis &apos;{1}&apos;.
        /// </summary>
        internal static string ClosingParensNotMatchFStringErrorMsg {
            get {
                return ResourceManager.GetString("ClosingParensNotMatchFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: empty expression not allowed.
        /// </summary>
        internal static string EmptyExpressionFStringErrorMsg {
            get {
                return ResourceManager.GetString("EmptyExpressionFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: expecting &apos;{0}&apos; but found &apos;{1}&apos;.
        /// </summary>
        internal static string ExpectingCharButFoundFStringErrorMsg {
            get {
                return ResourceManager.GetString("ExpectingCharButFoundFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: expecting &apos;{0}&apos;.
        /// </summary>
        internal static string ExpectingCharFStringErrorMsg {
            get {
                return ResourceManager.GetString("ExpectingCharFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: invalid conversion character: {0} expected &apos;s&apos;, &apos;r&apos;, or &apos;a&apos;.
        /// </summary>
        internal static string InvalidConversionCharacterExpectedFStringErrorMsg {
            get {
                return ResourceManager.GetString("InvalidConversionCharacterExpectedFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: invalid conversion character: expected &apos;s&apos;, &apos;r&apos;, or &apos;a&apos;.
        /// </summary>
        internal static string InvalidConversionCharacterFStringErrorMsg {
            get {
                return ResourceManager.GetString("InvalidConversionCharacterFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: invalid expression.
        /// </summary>
        internal static string InvalidExpressionFStringErrorMsg {
            get {
                return ResourceManager.GetString("InvalidExpressionFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid syntax.
        /// </summary>
        internal static string InvalidSyntaxErrorMsg {
            get {
                return ResourceManager.GetString("InvalidSyntaxErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: lambda must be inside parentheses.
        /// </summary>
        internal static string LambdaParenthesesFstringErrorMsg {
            get {
                return ResourceManager.GetString("LambdaParenthesesFstringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot mix bytes and nonbytes literals.
        /// </summary>
        internal static string MixingBytesAndNonBytesErrorMsg {
            get {
                return ResourceManager.GetString("MixingBytesAndNonBytesErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use named assignment with {0}.
        /// </summary>
        internal static string NamedAssignmentWithErrorMsg {
            get {
                return ResourceManager.GetString("NamedAssignmentWithErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named expression must be parenthesized in this context.
        /// </summary>
        internal static string NamedExpressionCtxtErrorMsg {
            get {
                return ResourceManager.GetString("NamedExpressionCtxtErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string expression part cannot include &apos;#&apos;.
        /// </summary>
        internal static string NumberSignFStringExpressionErrorMsg {
            get {
                return ResourceManager.GetString("NumberSignFStringExpressionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: single &apos;}&apos; is not allowed.
        /// </summary>
        internal static string SingleClosedBraceFStringErrorMsg {
            get {
                return ResourceManager.GetString("SingleClosedBraceFStringErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f-string: unmatched &apos;{0}&apos;.
        /// </summary>
        internal static string UnmatchedFStringErrorMsg {
            get {
                return ResourceManager.GetString("UnmatchedFStringErrorMsg", resourceCulture);
            }
        }
    }
}
