//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Python.Analysis.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Python.Analysis.Tests.TestStrings", typeof(TestStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class NotImplementedType(object):
        ///    __class__ = NotImplementedType
        ///    def __init__(self, *args, **kwargs):
        ///        pass
        ///    
        ///    @classmethod
        ///    def __init_subclass__(cls):
        ///        &apos;This method is called when a class is subclassed.\n\nThe default implementation does nothing. It may be\noverridden to extend subclasses.\n&apos;
        ///        return None
        ///    
        ///    def __reduce__(self):
        ///        return &apos;&apos;; return ()
        ///    
        ///    def __repr__(self):
        ///        &apos;Return repr(self).&apos;
        ///        return &apos;&apos;
        ///    
        ///    @cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuiltInModuleStubContent {
            get {
                return ResourceManager.GetString("BuiltInModuleStubContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import _msi as _mod__msi
        ///import builtins as _mod_builtins
        ///
        ///AMD64 = False
        ///class Binary(_mod_builtins.object):
        ///    __class__ = Binary
        ///    __dict__ = {}
        ///    def __init__(self, fname):
        ///        pass
        ///    
        ///    @classmethod
        ///    def __init_subclass__(cls):
        ///        &apos;This method is called when a class is subclassed.\n\nThe default implementation does nothing. It may be\noverridden to extend subclasses.\n&apos;
        ///        return None
        ///    
        ///    __module__ = &apos;msilib&apos;
        ///    def __repr__(self):
        ///        return &apos;&apos;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsiLibStubContent {
            get {
                return ResourceManager.GetString("MsiLibStubContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import _io as _mod__io
        ///import builtins as _mod_builtins
        ///import types as _mod_types
        ///
        ///def __breakpointhook__():
        ///    &apos;breakpointhook(*args, **kws)\n\nThis hook function is called by built-in breakpoint().\n&apos;
        ///    pass
        ///
        ///def __displayhook__():
        ///    &apos;displayhook(object) -&gt; None\n\nPrint an object to sys.stdout and also save it in builtins._\n&apos;
        ///    pass
        ///
        ///__doc__ = &quot;This module provides access to some objects used or maintained by the\ninterpreter and to functions that interact strongly with the interpret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SysStubContent {
            get {
                return ResourceManager.GetString("SysStubContent", resourceCulture);
            }
        }
    }
}
